theme: jekyll-theme-minimal
title: CV
description: Last updated: 1 Jul 2023
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
